# This file is kept for reference but not used with Deno Deploy
# The D1 database is accessed via Cloudflare REST API
# KV storage is now handled by Deno KV

# Cloudflare Resources (for reference):
# D1 Database: grus (d616e1fe-17e6-4320-aba2-393a60167603)
# Note: KV Namespace no longer needed - using Deno KV instead