#!/usr/bin/env -S deno run --allow-read --allow-write

/**
 * Setup Git hooks for pre-commit linting and formatting
 * Similar to Husky but using Deno's built-in tools
 */

import { ensureDir, exists } from "$std/fs/mod.ts";
import { join } from "$std/path/mod.ts";

const GIT_HOOKS_DIR = ".git/hooks";
const PRE_COMMIT_HOOK = "pre-commit";

const preCommitScript = `#!/bin/sh
# Pre-commit hook for Deno project
# Auto-generated by setup-hooks.ts

echo "🔍 Running pre-commit checks..."

# Run lint-staged equivalent
deno task lint-staged

# Check if there are any changes after formatting
if ! git diff --quiet --exit-code; then
  echo "📝 Files were formatted. Please review and commit the changes."
  echo "💡 Tip: Run 'git add .' to stage the formatted files"
  exit 1
fi

echo "✅ Pre-commit checks passed!"
`;

async function setupGitHooks() {
  try {
    // Check if we're in a git repository
    if (!(await exists(".git"))) {
      console.error("❌ Not a git repository. Please run 'git init' first.");
      Deno.exit(1);
    }

    // Ensure hooks directory exists
    await ensureDir(GIT_HOOKS_DIR);

    // Create pre-commit hook
    const hookPath = join(GIT_HOOKS_DIR, PRE_COMMIT_HOOK);
    await Deno.writeTextFile(hookPath, preCommitScript);

    // Make the hook executable
    await Deno.chmod(hookPath, 0o755);

    console.log("✅ Git hooks setup successfully!");
    console.log(`📁 Created: ${hookPath}`);
    console.log("\n🎯 Pre-commit hook will now:");
    console.log("  • Format code with deno fmt");
    console.log("  • Run linter with deno lint");
    console.log("  • Type check with deno check");
    console.log("  • Only process staged files");
    console.log("\n💡 To bypass hooks temporarily: git commit --no-verify");
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error("❌ Failed to setup Git hooks:", msg);
    Deno.exit(1);
  }
}

if (import.meta.main) {
  await setupGitHooks();
}